defaultName: "Developer"

# Database settings.
database:

  driverClass: org.h2.Driver
  user: sa
  password: sa
  # the JDBC URL
  url: jdbc:h2:./target/ts-task-service
  properties:
    hibernate.show_sql: true
    hibernate.format_sql: true
    hibernate.use_sql_comments: true

logging:
  loggers:
    org.hibernate.SQL:
      level: DEBUG
      type: TRACE
